### ISSUE TITLE
Add filler option 

### ISSUE THREAD

**Issue by ShoaibKhanali** [ni3x/aniyomi-extensions#11]
### Source name

Torrentio Anime

### Source language

English 

### Describe your suggested feature

Can you Add filler options to Torrentio Anime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ni3x** [comment]
Filters are already present in Torrentio Anime. Update to the latest version. If you are not getting the latest update use the correct repo.

**Comment by ShoaibKhanali** [comment]
I'd like to point out that there are no filler options.

**Comment by REFLEXGAMING007** [comment]
Yeah same thing is happening with me. 
filters are not showing in 14.9

**Comment by ni3x** [comment]
You guys might be using another repo, where torrentio is maintained by someone else.

The official latest version is  14.7

**Comment by ShoaibKhanali** [comment]
![Screenshot_20241115-183152](https://github.com/user-attachments/assets/e837a3e9-07cd-400d-b2b1-b5b42626604a)

There is no such option

**Comment by ShoaibKhanali** [comment]
https://github.com/user-attachments/assets/a9086dd6-9dd2-4fb2-81d4-c6b167baf16c

There is no such option

**Comment by REFLEXGAMING007** [comment]
Thnx ni3x bro I was using wrong repo 

Also Shoaib bhai the filter option is right there tho on the top right corner.
![Screenshot_20241115-195232919 (1).jpg](https://github.com/user-attachments/assets/1d781cf7-da46-4215-b2a2-90e91954b46f)

**Comment by ShoaibKhanali** [comment]
I am saying filler

**Comment by REFLEXGAMING007** [comment]
Wait.... What's filler option?

What does it do?? I may have never seen that before 🤔

**Comment by ShoaibKhanali** [comment]
![Screenshot_20241115-213515](https://github.com/user-attachments/assets/2ed3f1ba-81f9-46a7-b9b9-9b8ecafd0519)
It just mark filler ep
