### ISSUE TITLE
Torrentio Anime can't bypass clo*dflar* no matter which user agent or IP or device it's being used on

### ISSUE THREAD

**Issue by REFLEXGAMING007** [ni3x/aniyomi-extensions#13]
### Source name

Torrentio Anime (Torrent / Debrid)

### Source language

English

### Source link

https://torrentio.strem.fun/configure

### Other details

Torrentio Anime can't bypass clo*dflar* no matter which user agent or IP or device it's being used on

So far I've tested this in almost all user agents,
in 4 devices including Rog phone 3, Redmi note 4, Redmi note 5 pro, Redmi 7A and in different IPs aswell.

Torrentio extension working smoothly, It's just Torrentio Anime extension that didn't bypass clo*dflar* no matter what. Torrentio website was down literally 12hrs ago by the way if that helps somehow.

Please fix it bro. It's pretty much the best torrent extension providing high quality videos and the only extension I use 😓🙏🙏

https://github.com/user-attachments/assets/e8addc5d-24a8-4b80-b15a-26c2168a7e04

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by ni3x** [comment]
I have been using AniList for listing anime catalog, but the frequent downtime of the AniList API due to its instability has become a significant issue. To address this, I recommend add anime to the library even when the AniList API is unavailable. This way, new episodes can still be accessed seamlessly during API outages. If these issues with the AniList API persist in future, I plan to switch to Kitsu when I get time.

**Comment by REFLEXGAMING007** [comment]
Wait I don't get it...

It's about Torrent io Anime extension failing to bypass clo*dflar*e no matter the user agent , IP or device 

Not AniList Api outages🤔

**Comment by ni3x** [comment]
Torrentio Api just provides  video list. Anilist is used to display catalogs like poster, title, description, etc.

**Comment by ni3x** [comment]
Not gonna add toggle, too much work.
