### ISSUE TITLE
Source request animetak

### ISSUE THREAD

**Issue by 3bakri0** [ni3x/aniyomi-extensions#14]
### Source name

animetak

### Source link

https://animeftak.shop/

### Source language

Arabic

### Other details

It is one of the fastest Arabic sites that download anime and episodes with subtitles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ni3x** [comment]
No support for any other sites then torrent and nsfw
