### ISSUE TITLE
Source request Anime3rb

### ISSUE THREAD

**Issue by HOS-MAX** [ni3x/aniyomi-extensions#16]
### Source name

Anime3rb

### Source link

www anime3rb.com

### Source language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ni3x** [comment]
No support for any other sites then torrent and NSFW
