### ISSUE TITLE
Ptorrent Extension does not show anything.

### ISSUE THREAD

**Issue by jyash8** [ni3x/aniyomi-extensions#5]
### Source information

PTorrent

### Source language

English

### Steps to reproduce

1. Search for anything in the extension.
2. Select any option in the results
3. Nothing to shown to download.
4. Stub! Toast message shown.

### Expected behavior

Some link like a episode or some video should shown 

### Actual behavior

List of episodes comes empty.

### Aniyomi version

r7809

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ni3x** [comment]
Aniyomi do not support torrent at. 

To stream torrent, you need to use [kuukiyomi](https://github.com/LuftVerbot/kuukiyomi)
