### ISSUE TITLE
Torrentio extension is not working

### ISSUE THREAD

**Issue by Curiousnewbie** [ni3x/aniyomi-extensions#6]
### Source information

Torrentio 14.1

### Source language

Multi

### Steps to reproduce

Open torrentio source
Choose any series
Play 1 episode

### Expected behavior

The video should play

### Actual behavior

It keep showing an error "loading failed"

### Aniyomi version

Preview r7814

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Curiousnewbie** [comment]
This is the errir it shows when try to open it in webview 

Web page not available
The web page at https://torrentio.strem.funtt15571732,show,/in/tv-show/agatha-house-of-harkness could not be loaded because:

net::ERR_NAME_NOT_RESOLVED![Screenshot_2024-09-21-14-05-55-628_xyz.jmir.tachiyomi.mi.debug.jpg](https://github.com/user-attachments/assets/d5679208-f961-459e-bb3f-179881ed87f0)

**Comment by ni3x** [comment]
Torrentio is not an streaming website. Its a API. So it will not anything in webview. 

Aniyomi currently do not support torrent streaming. To stream video in Aniyomi you need any supported Debrid subscription.
If you want to stream without  subscription try using [kuukiyomi](https://github.com/LuftVerbot/kuukiyomi) or [Dantotsu](https://github.com/rebelonion/Dantotsu).
