### ISSUE TITLE
Collab with Kohi-den/Almighty Hak

### ISSUE THREAD

**Issue by itsmechinmoy** [ni3x/aniyomi-extensions#7]
### Describe why this should be added

Well its hard to maintain a repo alone, so i request you to collab with them as they're trying there best to maintain the repo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ni3x** [comment]
I don't have any plans to collab at. I want to keep this repo only for **torrent extension** and maintenance few of NSFW extension.
