### ISSUE TITLE
HENTAI.LA SEARCH ENGINE ERROR

### ISSUE THREAD

**Issue by JipsonA** [ni3x/aniyomi-extensions#8]
### Source information

Hentai.la "Spanish"

### Source language

Spanish

### Steps to reproduce

![Screenshot_2024-10-20-12-30-31-399_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/9f657b8c-0203-4ed0-84a0-245fa4792973)

### Expected behavior

Debería busca el hentai pero no lo busca y sale error así llevo desde dias

### Actual behavior

El hentai existe en la web pero no aparece en la app

### Aniyomi version

0.15.2.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ni3x** [comment]
I don't maintain or support mentioned extension.
