### ISSUE TITLE
Nyaa extension doesn't work

### ISSUE THREAD

**Issue by Hikari2w2** [ni3x/aniyomi-extensions#9]
### Source information

Nyaa si extension 14.1

### Source language

English 

### Steps to reproduce

Search for any torrent
Open it
It won't load the content, I'm getting this error instead: "Stub!"
![Screenshot_2024-10-22-16-01-20-884_com dark animetailv2](https://github.com/user-attachments/assets/7218d1a8-3fb1-44ff-8e66-8d462e7d4b89)

### Expected behavior

..

### Actual behavior

..

### Aniyomi version

Latest

### Android version

Android 11...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ni3x** [comment]
Aniyomi do not support torrent  at, use [kuukiyomi](https://github.com/LuftVerbot/kuukiyomi) or [Animetail](https://github.com/Dark25/Animetail2)

**Comment by Hikari2w2** [comment]
I'm using Animetail and it aint working as well

**Comment by ni3x** [comment]
[Animetail](https://github.com/Dark25/Animetail2) torrent code is not updated to latest  from [kuukiyomi](https://github.com/LuftVerbot/kuukiyomi)

**Comment by Hikari2w2** [comment]
I see, I'll test it on Kukiyomi then, thanks for the reply
